[pytest]

testpaths = tests
python_files = test_*.py
python_functions = test_*

addopts =
	-v
	--strict-markers
	--tb=short

markers =
	smoke: Smoke test cases
	sanity: Sanity test cases
	regression: Regression test cases
	testrail(case_id): TestRail case id mapping
